- .github/workflows/create-mentioning-comment.yml
- README.md
- scripts/mentioning-comment-handler.rb
- templates/.github/workflows/trigger-mentioning-comment.yml
This PR completes the work on the automatic mentioning system, including the case of PR's.
> Allow group mentioning from within PR's

- groups/dic-iit.yml
> AugustoFrancisco no longer a DIC member

- templates/.github/workflows/trigger-mentioning-comment.yml
> Update version of repository-dispatch

- groups/dic-iit.yml
Giovanni has been added as a new member and Giulio was added in the software development group (I did not do in the beginning, and I was wrong)
> Added Giovanni Pizzolante and Giulio Romualdi

- scripts/check-automated-repositories.rb
- scripts/mentioning-comment-handler.rb
- scripts/outside-collaborators-handler.rb
This PR introduces a safeguard to correctly handle the GH rate limit.
When we hit the limit, the actions will be able to wait until the reset take place.
> Add guard to handle rate limit

- scripts/check-automated-repositories.rb
- scripts/helpers.rb
- scripts/mentioning-comment-handler.rb
- scripts/outside-collaborators-handler.rb
Simply streamline code using a helper file.
> Add scripts helpers

- repos/cad-mechanics.yml
- repos/mechatronics.yml
As per title this PR adds one user to the mechanical repositories.
> Add one user to the mechanical repositories

- groups/dic-iit.yml
> Some updates to DIC electronics and mechanics

- groups/dic-iit.yml
> Added Razza and Di Natale

- groups/dic-iit.yml
Added @fabiodinatale to the DIC `mech` group.
cc @DanielePucci
> Add DIC user to the mech group

- FAQ.md
- README.md
- repos/cad-mechanics.yml
- repos/calibration-ft-sensors.yml
- repos/electronics-boards.yml
- repos/icub-snapshots.yml
- repos/mechatronics.yml
- repos/physical-modeling.yml
- repos/purchases.yml
- repos/python-cameras.yml
- repos/slurm-cluster.yml
- repos/sw-distro-management.yml
- repos/task-force-miscellanea.yml
- repos/tickets.yml
- scripts/check-automated-repositories.rb
- scripts/outside-collaborators-handler.rb
Better off using _permissions_ instead of _permission_.
cc @maggia80 @lornat75 @DanielePucci @fiorisi
> Fixed key "permissions"

- scripts/outside-collaborators-handler.rb
This PR changes the behavior of the handler while dealing with pending invitations.
Pending invitations are removed only for those collaborators no longer requested.
As a result, stale invitations of collaborators are not renewed.
Fix #39.
> At startup, only remove invitations of collaborators no longer requested

- groups/dic-iit.yml
> Added Italo Belli

- repos/teams-repos.yml
Add Augusto Francisco to the `dev` repository.
> Add user to the Dev repository

- groups/dic-iit.yml
- repos/study-mbd-amc-bldc.yml
This PR allows DIC access to our repo containing the development of the FOC via MBD.
cc @DanielePucci
> Access to study-mbd-amc-bldc

- README.md
- repos/teams-repos.yml
> Streamline YAML files with anchors and aliases

- groups/hsp-iit.yml
> New member

- repos/cad-mechanics.yml
> Add user with read permission.

- repos/cad-mechanics.yml
> Add user with read permission in cad-mechanics

- groups/dic-iit.yml
> Added Gatti and Grieco, and removed Duan

- groups/dic-iit.yml
- repos/cad-mechanics.yml
- repos/calibration-ft-sensors.yml
- repos/electronics-boards.yml
- repos/electronics-legacy.yml
- repos/ergocub-design-head.yml
- repos/hpc-cluster.yml
- repos/mechatronics.yml
- repos/physical-modeling.yml
- repos/purchases.yml
- repos/study-fw-toolchain.yml
- repos/study-mbd-amc-bldc.yml
- repos/sw-distro-management.yml
- repos/task-force-miscellanea.yml
- repos/temporary-external.yml
- repos/tickets.yml
As per the title.
cc @DanielePucci
> RL name updated from `dic-iit` to `ami-iit`

- repos/ergocub-gazebo-simulations.yml
> Added collaborators to ergocub-gazebo-simulations

- groups/ami-iit.yml
As per title. 
cc @DanielePucci
> Add AMI user to mech group

- scripts/helpers.rb
- scripts/outside-collaborators-handler.rb
This PR fixes the errors detected while pages services are running.
Also, the handling of the response is streamlined.
> Handle rate limiter for paged services

- groups/ami-iit.yml
> Added Mohamed Babiker Mohamed ELOBAID

- repos/ergocub-design-joint.yml
> `ergocub-design-joint`

- groups/ami-iit.yml
As per the title. This was missing and I noticed it because I could not CC him in the purchase
> Added  kouroshD in the list of seniors

- groups/ict-iit.yml
- repos/tickets.yml
This PR adds up the infrastructure for including our ICT personnel.
cc @mbrunettini
> Get ready for dealing with `ict-iit`

- groups/ami-iit.yml
> Added Andrea Testa

- groups/ami-iit.yml
> Added Marco Caianilello

- groups/ami-iit.yml
> Removing Tong Hui

- groups/ami-iit.yml
> Added Cheng Guo

- groups/ami-iit.yml
> Added Riccardo Zuppetti

- groups/ami-iit.yml
> Added Evelyn Anne D'elia 

- groups/ami-iit.yml
> Adding EhsanRanjbari

- groups/ami-iit.yml
> Added Sander Ruijters

- repos/calibration-ft-sensors.yml
> Give to isorrentino the read permission on calibration-ft-sensors repo

- scripts/check-automated-repositories.rb
- scripts/delete-invitations.rb
- scripts/mentioning-comment-handler.rb
- scripts/outside-collaborators-handler.rb
> Handle empty entries in `groups`

- repos/electronics-boards.yml
- repos/ergocub-design-joint.yml
- repos/ergocub-design-lowerarm.yml
- repos/mechatronics.yml
- repos/teams-repos.yml
- scripts/check-automated-repositories.rb
- scripts/delete-invitations.rb
- scripts/mentioning-comment-handler.rb
- scripts/outside-collaborators-handler.rb
> Fixed use of `compact!`

- groups/ami-iit.yml
fyi @CarlottaSartore @DanielePucci @pattacini
> Add missing users from ami-iit/sw-dev group

- groups/ami-iit.yml
Visiting student from Virginia Tech under the supervision of Alexander Leonessa
> Added Connor Herron

- groups/ami-iit.yml
> Add Lorenzo Moretti to AMI groups

- groups/ami-iit.yml
> Added Francesca Bruzzone

- groups/ami-iit.yml
> Added Elobaid into purchase

- groups/ami-iit.yml
He is the new member of the Artificial Mechanical Intelligence research line for IIT-Danieli Joint Lab. For the specific sub-groups in which he is member, I copied the one in which Baljinder (that is the other member of AMI/IDJL) is already in.
fyi @DanielePucci
> Add Giovanni Fregonese (@giotherobot) to the ami-iit.yml file

- repos/purchases.yml
- repos/tickets.yml
> removed LaMelis

- repos/setups-os-configuration.yml
As per the title.
cc @davidelasagna @s-dafarra
> Add access to `setups-os-configuration`

- groups/ami-iit.yml
> Added Tatarelli and Fiori

- scripts/check-automated-repositories.rb
- scripts/delete-invitations.rb
- scripts/outside-collaborators-handler.rb
> Safeguarding archived repos

- groups/ami-iit.yml
@gabrielenava I also added Davide and Saverio.
> Add new AMI members that joined in March 2023

- groups/ami-iit.yml
> Added Filippo Ferretti

- groups/ami-iit.yml
> Adding Yuchuan Lu

- groups/ami-iit.yml
> Added Filippo Passerini

- groups/ami-iit.yml
> Added Shabarish Pillai

- groups/ami-iit.yml
> Aggiunto Tatarelli e Fiori a purchases

- groups/hsp-iit.yml
Added Giuseppe Stracquadanio removed Jabrail Chumakov.
> updates hsp team

- groups/ami-iit.yml
- repos/calibration-ft-sensors.yml
As per the title.
Group created to regulate access to FT calibration repo, in particular.
cc @DanielePucci @evalli-iit
> Added AMI iFeel group

- groups/ami-iit.yml
- repos/project-raicam-smart-ecargo.yml
> Add `ami-iit/raicam`

- groups/raicam.yml
- repos/project-raicam-smart-ecargo.yml
cc @MR-Raicam @Luca-Soma @FSantoma @salvi-mattia @maggia80
> Add RAICAM members

- scripts/mentioning-comment-handler.rb
> Handle empty body when mentioning

- groups/ami-iit.yml
Davide, who will work on the RAICAM project, is added here
> Added Davide Barbone

- repos/study-r1-ergomorphing.yml
> Grant access to `study-r1-ergomorphing` repo

- repos/project-jl-camozzi.yml
- repos/project-jl2-camozzi.yml
> Add MARC to JL2 repo

- groups/ami-iit.yml
- groups/hsp-iit.yml
- repos/study-r1-ergomorphing.yml
- repos/sw-management.yml
@xenvre and @lrapetti are leaving IIT.
Good luck guys! Wish you all the best!
> Remove alumni

- groups/ami-iit.yml
> Aggiunto Lorenzo Conti

- groups/ami-iit.yml
As they may want to generate ergoCub URDF models, see https://github.com/icub-tech-iit/ergocub-software/pull/229#discussion_r1533641951 .
> ami-iit: Add scrum masters of ergocub-related teams to ami-iit/mech

- groups/ami-iit.yml
I added him to `ami-iit/everyone`, `ami-iit/mech` and `ami-iit/ergocub`, we can add him to more groups in the future. @GiulioRomualdi @evalli-iit
> Add new member Alex Coppola to ami-iit.yml

- groups/hsp-iit.yml
Reverts icub-tech-iit/outside-collaborators#226
Reverting due to misunderstandings
> Revert "Added Alex Coppola to hsp-iit.yml"

- groups/ami-iit.yml
So he can monitor some orders related to Camozzi Joint Lab
fyi @DanielePucci
> Add STaliani to ami-iit/purchases

- groups/ami-iit.yml
> Allowing L'Erario and Bergonti as masters

- groups/ami-iit.yml
> Added Ferigo as master

- repos/teams-repos.yml
> Add AMI collabs to FIVE

- groups/ami-iit.yml
@g-cervettini also works on the ergoCub project.
fyi @DanielePucci
> Add Guglielmo Cervettini to ami-iit/ergocub group

- groups/ami-iit.yml
> Added Forleo to purchase

- groups/ami-iit.yml
Bruno Trombetta is a new member of the AMI research line.
> Add Bruno Trombetta to AMI group

- groups/ami-iit.yml
> Added Arianna Pietrasanta

- groups/ami-iit.yml
> Added Ilona Straub

- groups/hsp-iit.yml
- repos/study-r1-ergomorphing.yml
> Add fbrand-new to study-r1-ergomorphing.yml

- repos/teams-repos.yml
Also @GiulioRomualdi is collaborating in the mixed AMI/FIVE team.
cc @pattacini @valegagge @DanielePucci @maggia80
> Add GiulioRomualdi to FIVE
